# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'AFNetworking', '~> 2.5.0'
pod 'Masonry', '~> 0.5.3'
pod 'MBProgressHUD', '~> 0.5'
pod 'iCarousel', '~> 1.7.6'
pod 'JSONModel', '~> 1.1.0'
pod 'Heap', '~> 2.1.5'
pod 'CardIO', '~> 5.1.1'
pod 'AWSiOSSDKv2'

pod 'SWTableViewCell', '~> 0.3.7'
pod 'Stripe'

pod 'JSBadgeView'

pod 'pop', '~> 1.0'

pod 'Leanplum-iOS-SDK'
pod 'ZendeskSDK'

pod 'SDWebImage', '~>3.7'

pod  'Fabric'

pod 'Crashlytics'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'